### ISSUE TITLE
Persistent Data

### ISSUE THREAD

**Issue by schrieveslaach** [aixigo/PREvant#123]
At the moment PREvant does not provide any option to ensure that the data of a service or companion will be persisted. For example, if someone operates a PostgreSQL database on a Kubernetes cluster and the container will be moved to another node, all data will be lost for this application (Kafka is another example).

Further, people report to me personally, that they need a way of sharing data between different services or companions (even when [Microservices shouldn't be synchronized via file system because it is the worst option](https://youtu.be/bbotWkCLuF0?t=355))

Anyways, PREvant should allow that services or companions are able to store data. Here are some ideas:

- The `registry.rs` can be enhanced not just returning the port but also including the list of exposed volumes (according to the [spec](https://github.com/moby/moby/blob/a30990b3c8d0d42280fa501287859e1d2393a951/image/spec/v1.md#image-json-description)
- If configured, PREvant can create volumes in the case of Docker backend and PVCs in the case of Kubernetes backend for companions automatically.
  - What kind of PVC should be configurable for Kubernetes backend
- Hooks should provide a mechanism to share persistent data

**Comment by samuchila** [comment]
@schrieveslaach I have managed to implement persistence for both docker and kubernetes.
I would like to address the second point in the comment above. The best configuration is to create a PVC tied to the `local-path` storage class. (This is created by default when k3s cluster is created, along with local-path-provisioner deployed by default). It has advantages over using host_path and provides an extra degree of flexibility in provisioning.
Additionally, a global config will be used to provide the storage quantity of the provisioned path.

**Comment by schrieveslaach** [comment]
@samuchila, I see you are making progress and I think [my comment here](https://github.com/aixigo/PREvant/pull/127#pullrequestreview-1549215998) should provide some basic structuring to be able to serve all mentioned use cases within this issue which can be implemented first for Docker and then for Kubernetes. Please, have a look and lets focus on Docker first.
